testing/halkhata_app/HALKHATA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('halkhata_app.urls', namespace='halkhata')),
    path('activity/', include('activity.urls', namespace='activity')),
]

testing/halkhata_app/activity/urls.py
from django.urls import path
from . import views


app_name = 'activity'

urlpatterns = [
    path('list/', views.activity_list, name='activity_list'),
    path('detail/<str:type>/<int:id>/', views.activity_details, name='activity_details'),
    path('add_activity/', views.add_activity, name='add_activity'),
    path('add_activity/<str:type>/', views.add_activity, name='add_activity_by_type'),

]

testing/halkhata_app/halkhata_app/urls.py
from django.urls import path

from . import views

app_name = 'halkhata_app'

urlpatterns = [
    path('', views.home, name='home'),
]

testing/halkhata_app/activity/models.py
from django.contrib.admin.decorators import register
from django.db import models
from django.db.models.fields import TimeField
from django.urls import reverse
import datetime


class Activity(models.Model):
    """A days all activitys"""
    date = models.DateField(auto_now_add=True)


    class Meta:
        ordering = ('-date',)
        verbose_name_plural  = 'activities'





class Ride(models.Model):
    type = 'ride'
    activity = models.ForeignKey(Activity, related_name='rides', on_delete=models.CASCADE)
    name = models.CharField(max_length=150, null=True, blank=True)
    distance = models.DecimalField(max_digits=6, decimal_places=2)
    duration = models.DurationField()
    elev_gain = models.IntegerField()
    avg_speed = models.DecimalField(max_digits=6, decimal_places=2)
    cal_burned = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return "Ride"

    def get_absolute_url(self):
        return reverse('activity:activity_details', args=[self.type, self.id])


#test models.
class Run(models.Model):
    type = 'run'
    activity = models.ForeignKey(Activity, related_name='runs', on_delete=models.CASCADE)
    name = models.CharField(max_length=150, null=True, blank=True)
    distance = models.DecimalField(max_digits=6, decimal_places=2)
    duration = models.DurationField()
    elev_gain = models.IntegerField()
    avg_speed = models.DecimalField(max_digits=6, decimal_places=2)
    cal_burned = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return "Run"

    def get_absolute_url(self):
        return reverse('activity:activity_details', args=[self.type, self.id])



class Walk(models.Model):
    type = 'walk'
    activity = models.ForeignKey(Activity, related_name='walks', on_delete=models.CASCADE)
    name = models.CharField(max_length=150, null=True, blank=True)
    distance = models.DecimalField(max_digits=6, decimal_places=2)
    duration = models.DurationField()
    elev_gain = models.IntegerField()
    avg_speed = models.DecimalField(max_digits=6, decimal_places=2)
    cal_burned = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return "Walk"

    def get_absolute_url(self):
        return reverse('activity:activity_details', args=[self.type, self.id])


class Exercise(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField()
    muscle_group = models.CharField(max_length=50)
    deficulty_level = models.IntegerField()

    def __str__(self):
        return self.name

testing/halkhata_app/halkhata_app/models.py
from django.db import models

# Create your models here.

testing/halkhata_app/activity/forms.py
from django import forms
from django.db.models import fields

from .models import Ride


class AddRideForm(forms.ModelForm):
    class Meta:
        model = Ride
        fields = ['name', 'distance', 'duration',
                  'avg_speed', 'elev_gain', 'cal_burned']

testing/halkhata_app/activity/views.py
from django.db.models.fields import DateField
from django.shortcuts import render, redirect
from .models import Ride, Run, Walk, Activity
from .forms import AddRideForm
from django.shortcuts import get_object_or_404, HttpResponse
import datetime

def activity_list(request):
    dates = Activity.objects.all()
    
    activities = []

    for date in dates:
        for walk in date.walks.all():
            activities.append(walk)
        for run in date.runs.all():
            activities.append(run)
        for ride in date.rides.all():
            activities.append(ride)
    print(activities)

    return render(request, 'activity/activity_list.html',{'activities':activities})



def activity_details(request, type, id):

    if type == 'ride':

        activity = get_object_or_404(Ride, pk = id)

    elif type == 'walk':
    
        activity = get_object_or_404(Walk, pk = id)

    elif type == 'run':
    
        activity = get_object_or_404(Run, pk = id)


    return render(request, 'activity/activity_detail_ride.html', {'activity':activity})


def add_activity (request, type = None):
    #If it's a new day then create a new Activity object
    if not Activity.objects.all():
        latest_activity = Activity()
        latest_activity.save()
        

    elif Activity.objects.all():
        latest_activity = Activity.objects.all()[0]
     
        if latest_activity.date != datetime.datetime.now().date():
            latest_activity = Activity()
            latest_activity.save()

    #add the new activity according to its type.
    time_now = datetime.datetime.now().time()
    today = datetime.datetime.now().date()

    if type=='ride':
        if request.method != 'POST':
            form = AddRideForm()
        else:
            form = AddRideForm(data=request.POST)
            print('here')
            if form.is_valid():
                print("valid\n")
                new_ride = form.save(commit=False)
                new_ride.date = latest_activity
                new_ride.save()
                return redirect(new_ride)
            
        return render(request, 'activity/add_ride.html', {'form':form, 'date':today, 'time':time_now})


    return render(request, 'activity/add_activity.html')

testing/halkhata_app/halkhata_app/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'halkhata_app/home.html')

testing/halkhata_app/activity/templates/activity/activity_detail_ride.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
<section class="ride">

    <div class="heading">
        <p class="date">date: {{activity.date}} </p>
        <p class="date">time:{{activity.time}} </p>
        <h1 class="title">{{activity.type}}</h1>
    </div>
    <div id="distance" class="info">
        <h2 class="main-info-value">{{activity.distance}}</h2>
        <p class="main-info-type">Distance</p>
    </div>
    <div id="avg_speed" class="info">
        <h2 class="main-info-value">{{activity.avg_speed}}</h2>
        <p class="main-info-type">Avg. Speed</p>
    </div>
    <div id="duration" class="info">
        <h2 class="main-info-value">{{activity.duration}}</h2>
        <p class="main-info-type">Duration</p>
    </div>
    <div id="elev_gain" class="info">
        <h2 class="main-info-value">{{activity.elev_gain}}</h2>
        <p class="main-info-type">Elev. Gained</p>
    </div>
    <div id="cal_burn" class="info">
        <h2 class="main-info-value">{{activity.cal_burned}}</h2>
        <p class="main-info-type">Calories Burned</p>
    </div>
    
</section>
{% endblock container %}

testing/halkhata_app/activity/templates/activity/activity_list.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
<section>
    <div class="cta-section">
        <form action="#">
            <label for="jump-to-date">Jump to date:</label>
            <input class="date" type="date">
            <input type="submit">
        </form>

        <a href="{% url 'activity:add_activity' %}" class="cta-btn">
            +ADD ACTIVITY
        </a>
    </div>
    <!--end cta section-->


    <ul class="activity-list">
        {% for activity in activities %}
        <li class="activity"><a href="{{activity.get_absolute_url}}">
            <p class="date">date: {{activity.date}}</p>
            <h1 class="title">{{activity.type}}</h1>
            <div class="info">
                <h2 class="main-info-value">{{activity.distance}}km</h2>
                <p class="main-info-type">Distance</p>
            </div>
        </a>
    </li>
        {% endfor %}
    </ul>
    <!--end activity list-->

</section>
{% endblock container %}

testing/halkhata_app/activity/templates/activity/add_activity.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
<section class="select-type">
    <p>Please select the type of your activity:</p>
    <a href="#" id="workout">
        <h1 class="title">workout</h1>
    </a>
    <a href="{% url 'activity:add_activity_by_type' 'ride' %}" id="ride">
        <h1 class="title">ride</h1>
    </a>
    <a href="#" id="run">
        <h1 class="title">run</h1>
    </a>
    <a href="#" id="walk">
        <h1 class="title">walk</h1>
    </a>
</section>
{% endblock container %}

testing/halkhata_app/activity/templates/activity/add_ride.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
<section class="ride">
<form action="{% url 'activity:add_activity_by_type' 'ride' %}" method="post">
    <div class="heading">
        <p class="date">date: {{date}} </p>
        <p class="date">time:{{time}} </p>
        <h1 class="title">ride</h1>
    </div>
    <input type="text" placeholder="name">
    <div id="distance" class="info">
        <h2 class="main-info-value"><input type="number" placeholder="0">km</h2>
        <p class="main-info-type">Distance</p>
    </div>
    <div id="avg_speed" class="info">
        <h2 class="main-info-value"><input type="number" placeholder="0">km/h</h2>
        <p class="main-info-type">Avg. Speed</p>
    </div>
    <div id="duration" class="info">
        <h2 class="main-info-value"><input type="number" placeholder="0">s</h2>
        <p class="main-info-type">Duration</p>
    </div>
    <div id="elev_gain" class="info">
        <h2 class="main-info-value"><input type="number" placeholder="0">m</h2>
        <p class="main-info-type">Elev. Gained</p>
    </div>
    <div id="cal_burn" class="info">
        <h2 class="main-info-value"><input type="number" placeholder="0"></h2>
        <p class="main-info-type">Calories Burned</p>
    </div>
    <input type="submit" value="ADD">
    {% csrf_token %}
</form>
</section>
{% endblock container %}

testing/halkhata_app/halkhata_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>HalKhata</title>
</head>
<body>
    

        <header>
            <div class="nav-bar">
                <nav>
                    <div class="logo">
                        <a href="{% url 'halkhata:home' %}">Hal<span>khata</span></a>
                    </div>
                    <ul id="primary-nav">
                        <li class="selected"><a class="nav-link" href="{% url 'activity:activity_list' %}">Activity</a></li>
                        <li><a href="#" class="nav-link">Meal</a></li>
                        <li><a href="#" class="nav-link">Spending</a></li>
                        <li><a href="#" class="nav-link">Coding</a></li>
                    </ul>
                    <!-- secondary-nav -->
                </nav>
            </div>
        </header>
        <div class="container">
        {% block container %}{% endblock container %}
    </div>
</body>
</html>

testing/halkhata_app/halkhata_app/templates/halkhata_app/home.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
<section class="hero">

    <div class="hero-text">
        <h1>halkhata</h1>
        <p>your personal log book</p>
    </div>

    <img src="{% static 'images/hero_illustration.svg' %}" alt="hero image">

</section>
{% endblock container %}